### PR TITLE
Fill fsm module `__init__.py` file

### PR DESCRIPTION
**Pull request by dsodx**
# Description

Fill `fsm/__init__.py` to simplify imports.
For example use
```python
from aiogram.fsm import FSMContext, StatesGroup, State
from aiogram.fsm import FSMStrategy, apply_strategy
from aiogram.fsm import FSMContextMiddleware
```
instead of
```python
from aiogram.fsm.context import FSMContext
from aiogram.fsm.state import State, StatesGroup
from aiogram.fsm.strategy import FSMStrategy, apply_strategy
from aiogram.fsm.middleware import FSMContextMiddleware
```
NOTE: You should still use

```python

from aiogram.fsm.storage.redis import RedisStorage
from aiogram.fsm.storage.memory import MemoryStorage
from aiogram.fsm.storage.base import BaseStorage
```
to import storages.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- [x] Test A: `pytest tests`: OK

- [x] Test B: Create `test_b.py` at the root of the project, then fill it with:
```python
from aiogram.fsm import (
    FSMContext,
    State,
    StatesGroup,
    StatesGroupMeta,
    FSMContextMiddleware,
    FSMStrategy,
    apply_strategy,
)
```
and run: OK

**Test Configuration**:
* Operating System: `Windows 11 22H2`
* Python version: `3.11.3`

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by dsodx** [comment]
Ready for review.

**Comment by sheldygg** [comment]
while RedisStorage was not in init, redis was not a required dependency, but now that you have added it to init, redis has become a required dependency

**Comment by dsodx** [comment]
> redis has become a required dependency

Same with magic_filter.

**Comment by dsodx** [comment]
OK. I'll try to fix it.

**Comment by dsodx** [comment]
Fixed.

**Comment by sheldygg** [comment]
i still think its a bad practice because if i try to import RedisStorage and redis is not installed i will get an error that doesn't explain anything

ImportError: Cannot import name 'RedisStorage' from 'aiogram.fsm' (aiogram\fsm\__init__.py)

you need to somehow explain that he does not have redis installed

**Comment by sheldygg** [comment]
well, or all the same, @JrooTJunior will arrange this option

**Comment by sheldygg** [comment]
I think the best option would be to just delete everything related to redis from __init__.py and leave everything else as you did

**Comment by JrooTJunior** [comment]
I don't think so here is `__init__.py` is needed because in common case (separated by modules/packages) you shouldn't place storage, state definition and context usage at the same point.

Anyway if you remove the redis storage at all from the `__init__.py` that's mean  the redis module is not importable from this package at all.

**Comment by dsodx** [comment]
I removed storages from `__init__.py`.

**Comment by dsodx** [comment]
I find this to be a useful PR since, for example,

```python
from aiogram.fsm.context import FSMContext
```

and 

```python
from aiogram.fsm.state import State, StatesGroup
```

are often used together and my PR simplify it.

**Comment by dsodx** [comment]
@JrooTJunior is there any news?

**Comment by JrooTJunior** [comment]
I don't like this change in due to now the redis module is no more importable (still can be imported but is not exported by `__init__`)

**Comment by dsodx** [comment]
so yes, all storages are not exported into init.
